/**
 * In-app v1.6 MVP plan seeder.
 *
 * Used by the "Seed MVP plan" button inside Manage Epics. Creates the
 * 5 Epics (with stable slug ids) and the 22 user-story Features from
 * `tasks/v1.6-planning-system-design.md` §6, idempotently.
 *
 * Why an in-app button instead of a CLI script: HelmLogic ships via
 * Firebase App Hosting, no local dev env. Clicking from the deployed
 * app runs against the same Firestore the team is using.
 *
 * Auth: any signed-in non-sub-dealer user can run this — Firestore
 * rules already gate features+epics writes by isSubDealer(). The
 * button is in Manage Epics which is itself only reachable to non-
 * sub-dealers.
 */

import {
    addDoc,
    collection,
    doc,
    getDoc,
    getDocs,
    serverTimestamp,
    setDoc,
    type Firestore,
} from 'firebase/firestore';
import type { EpicColor, FeaturePriority, FeatureType } from '@/components/feature-tracking-board';

interface SeedEpic {
    /** Stable slug used as the doc id — features reference it via epicId. */
    id: string;
    title: string;
    shortLabel: string;
    description: string;
    color: EpicColor;
    order: number;
    status: 'planning' | 'active' | 'done';
}

interface SeedFeature {
    title: string;
    description: string;
    acceptanceCriteria: string[];
    type: FeatureType;
    priority: FeaturePriority;
    targetRelease: string | null;
    points: number | null;
    epicId: string;
}

const story = (role: string, want: string, so: string) =>
    `<p><strong>As a</strong> ${role}<br><strong>I want</strong> ${want}<br><strong>So that</strong> ${so}.</p>`;

const EPICS: SeedEpic[] = [
    { id: 'guided-configuration',   title: 'Guided Configuration & Quote Creation',     shortLabel: 'Guided Config', description: 'Validated configuration flow + branded customer-ready proposal output. The MVP cornerstone — emotional + technically accurate.',                                              color: 'blue',    order: 100, status: 'active'   },
    { id: 'pricing-accuracy',       title: 'Pricing Accuracy & Margin Protection',      shortLabel: 'Pricing',       description: 'All quote line pricing sourced from approved lists with audit trail; margin enforcement with GM override; post-contract variations.',                                          color: 'amber',   order: 200, status: 'planning' },
    { id: 'data-management',        title: 'Data Management & Sustainability',          shortLabel: 'Data',          description: 'Structured imports with versioning + manual approval; consistent internal data model; controlled crowdsourced suggestions with audit.',                                       color: 'violet',  order: 300, status: 'planning' },
    { id: 'promotions',             title: 'Promotions & Commercial Flexibility',       shortLabel: 'Promotions',    description: 'Manual promo entry across $/HP, $/foot, %, and fixed rebate forms; alerts when a quote includes an item with active promo.',                                                  color: 'emerald', order: 400, status: 'planning' },
    { id: 'security-extensibility', title: 'Security, Extensibility & Dealer Model',    shortLabel: 'Security',      description: 'Hull-only / engine-only / trailer-only quoting; brand & dealer isolation (no cross-brand or cross-dealer leakage); brand onboarding without code changes.',                  color: 'rose',    order: 500, status: 'planning' },
    { id: 'launch-prep-ops',        title: 'Launch Prep & Ops',                          shortLabel: 'Ops',           description: 'Non-code work that has to happen for HelmLogic to ship: training plan, data migration, legal review, AD/SMTP setup, content gathering, change management.',           color: 'slate',   order: 600, status: 'planning' },
];

const FEATURES: SeedFeature[] = [
    // Epic 1 — Guided Configuration (9 stories, 35 pts → v1.7)
    { title: '1.1.1 — Enforced Configuration Sequence',                       description: story('salesperson', 'to be guided through a fixed configuration sequence', 'I cannot accidentally build an invalid boat package'),                            acceptanceCriteria: ['Order: Hull → Manufacturer options → Engine(s) & rigging → Trailer → Dealer fit options & accessories → Dealer fit-out charge', 'Steps cannot be skipped', 'System always maintains a valid state'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 2, epicId: 'guided-configuration' },
    { title: '1.1.2 — Compatibility Rule Enforcement',                        description: story('salesperson', 'the system to prevent incompatible combinations', 'I never quote an unbuildable package'),                                              acceptanceCriteria: ['Hard rules between Hull ↔ Engine, Hull ↔ Trailer, Hull ↔ Manufacturer options', 'Invalid combinations cannot be saved', 'Invalid combinations cannot be quoted', 'User sees a clear validation error'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 3, epicId: 'guided-configuration' },
    { title: '1.1.3 — Multiple Quote Scenarios',                              description: story('salesperson', 'to create multiple quote versions for one customer', 'I can easily present alternatives'),                                              acceptanceCriteria: ['Quote can be duplicated into new versions', 'Versions are clearly labelled (e.g. Option A / Option B)', 'Only one version can be marked Finalised'], type: 'feature', priority: 'medium',   targetRelease: 'v1.7', points: 3, epicId: 'guided-configuration' },
    { title: '1.2.1 — Branded PDF Quote Generation',                          description: story('salesperson', 'the system to generate a professional customer-ready quote', 'I can present the boat as a premium ownership experience'),               acceptanceCriteria: ['Personalised salesperson message', 'Why Northside Marine + Life Beyond the Shore positioning', 'End-to-end ownership support', 'Brand & model story', 'Configured boat summary (visual, not SKU tables)', 'After-sales confidence & warranties', 'Finance & insurance (informational)', 'Value summary', 'No system IDs or SKU codes are visible'], type: 'feature', priority: 'critical', targetRelease: 'v1.7', points: 8, epicId: 'guided-configuration' },
    { title: '1.2.2 — Brand-Aware Content Injection',                         description: story('salesperson', 'brand-specific content to auto-populate', 'the quote is accurate and on-brand every time'),                                             acceptanceCriteria: ['Correct logos, imagery, and copy load per brand', 'No cross-brand content leakage'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 3, epicId: 'guided-configuration' },
    { title: '1.2.3 — Controlled Personalisation',                            description: story('salesperson', 'to personalise parts of the quote safely', 'the document remains professional and consistent'),                                         acceptanceCriteria: ['Only approved text sections are editable', 'Document structure cannot be broken'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'guided-configuration' },
    { title: '1.3.1 — Finalised Quote Locking',                               description: story('sales manager', 'finalised quotes to be locked', 'commercial integrity is preserved'),                                                                  acceptanceCriteria: ['Finalised quotes are read-only', 'Changes require a variation workflow'], type: 'feature', priority: 'medium',   targetRelease: 'v1.7', points: 1, epicId: 'guided-configuration' },
    { title: '1.3.2 — Contract Signing Pack Generation',                      description: story('salesperson', 'a complete signing pack generated automatically', 'the customer can sign without manual assembly'),                                     acceptanceCriteria: ['Pack includes: Final quote, Payment plan expectations, T&Cs, Configuration summary'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'guided-configuration' },
    { title: '1.3.3 — SharePoint Quote Storage',                              description: story('staff member', 'finalised quotes stored in SharePoint', 'customers can be supported when the salesperson is unavailable'),                              acceptanceCriteria: ['PDF is automatically written to SharePoint', 'Location is configurable', 'Access controlled by permissions', 'Requires Azure AD app registration + Files.ReadWrite.All on the target site'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'guided-configuration' },

    // Epic 1 expansion — Quote Lifecycle (1.4.x), Customer 360 / CRM (1.5.x), Comms (1.6.x), Operational dashboards (1.7.x)
    { title: '1.4.1 — Quote Lifecycle States',                                description: story('salesperson', 'quotes to progress through real states (Draft → Sent → Viewed → Accepted / Rejected / Lost / Expired)', 'I can see exactly where each customer is in the buying journey'),       acceptanceCriteria: ['Status enum extended beyond draft/finalised', 'State transitions logged with timestamp + actor', 'Visual state badge on quote card + detail sheet', 'Won / Lost reason capture'],                                                                                            type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'guided-configuration' },
    { title: '1.4.2 — Send Quote Action',                                     description: story('salesperson', 'a single action that sends a quote to the customer and records when it went out', 'I never lose track of which quotes are in front of which customers'),                            acceptanceCriteria: ['"Send" button on a draft quote', 'Email send when SMTP integration is live; otherwise a manual "mark sent" with note', 'Send timestamp + recipient stored on the quote', 'State auto-transitions to "Sent"'],                                                                  type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 3, epicId: 'guided-configuration' },
    { title: '1.4.3 — Acceptance Capture',                                    description: story('sales manager', 'to record customer acceptance of a quote (sales-rep marks for now, e-sig later)', 'we have a defensible record that the customer agreed to the price'),                          acceptanceCriteria: ['"Mark accepted" action on a sent quote', 'Acceptance timestamp + actor stored', 'State transitions to "Accepted"', 'Can attach a customer email/PDF screenshot as evidence', 'E-sig deferred to a future release'],                                                            type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 3, epicId: 'guided-configuration' },
    { title: '1.4.4 — Quote Validity / Expiry',                               description: story('salesperson', 'quotes to have an expiry date that auto-rolls them to "Expired" if not accepted in time', 'pricing snapshots stay commercially safe'),                                          acceptanceCriteria: ['Configurable validity period per brand (default 30 days)', 'Expiry date shown on the proposal PDF', 'Auto-transition to "Expired" past the date (cron or on-load)', 'Sales rep can manually extend with a reason'],                                                            type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 2, epicId: 'guided-configuration' },
    { title: '1.4.5 — Quote Versioning per Customer',                         description: story('salesperson', 'multiple quote versions for one customer linked together as Option A / B / C', 'the customer can compare alternatives and I can see them all in one place'),                       acceptanceCriteria: ['"Duplicate as new version" action on a quote', 'Sibling versions linked under the same customer', 'Customer detail sheet shows all versions of a single opportunity', 'Only one version can be Accepted'],                                                                  type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 5, epicId: 'guided-configuration' },
    { title: '1.5.1 — Customer Detail Sheet',                                 description: story('salesperson', 'a single page that shows everything about a customer: their details, every quote, every contract, every note', 'I never have to switch tools to remember a relationship'), acceptanceCriteria: ['Customer 360 view: profile + quotes + contracts + comms + notes timeline', 'Click-through to any artifact', 'Inline edit of customer fields'],                                                                                                                                  type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'guided-configuration' },
    { title: '1.5.2 — Customer Pipeline View',                                description: story('sales manager', 'a Kanban view of all customers grouped by lifecycle stage (lead → qualified → quoted → contracted → delivered)', 'I see at a glance where the team is and where things are stuck'), acceptanceCriteria: ['Kanban board: lead / active opp / quoted / contracted / delivered / lost', 'Drag a customer between stages', 'Filter by salesperson, brand, value', 'Stage colour-coded'],                                                                                                  type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 8, epicId: 'guided-configuration' },
    { title: '1.5.3 — Customer Notes Timeline',                               description: story('salesperson', 'to capture notes against a customer with a timestamp and author', 'context survives staff handovers'),                                                                                  acceptanceCriteria: ['Free-text note input on customer detail sheet', 'Timeline of all notes (and other interactions, see 1.6.1) sorted DESC', 'Author + timestamp captured automatically', 'Notes visible to anyone with access to the customer'],                                                  type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 3, epicId: 'guided-configuration' },
    { title: '1.5.4 — Customer Source Tracking',                              description: story('sales manager', 'to know how each customer found us (boat show, referral, web, walk-in)', 'we can measure marketing ROI'),                                                                          acceptanceCriteria: ['Source field on customer doc (enum + free-text override)', 'Source picker shown on first customer create', 'Source visible on customer detail sheet', 'Reports can group by source (post-MVP)'],                                                                                type: 'feature', priority: 'low',      targetRelease: 'v1.8', points: 2, epicId: 'guided-configuration' },
    { title: '1.5.5 — Trade-In Record',                                       description: story('salesperson', 'to capture the customer\'s trade-in vessel (make / model / year / condition / agreed value)', 'the trade-in flows through to the quote and the deposit calculation'),                acceptanceCriteria: ['Trade-in fields linked to customer + quote', 'Agreed trade-in value applied as a credit on the quote', 'Trade-in inspection notes + photos', 'Trade-in stays with the customer record after the deal'],                                                                          type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 3, epicId: 'guided-configuration' },
    { title: '1.5.6 — Spouse / Co-buyer Support',                             description: story('salesperson', 'to record a customer with a partner or co-buyer who also signs the contract', 'shared-ownership purchases are handled cleanly'),                                                       acceptanceCriteria: ['Customer doc supports a primary + secondary buyer', 'Both names appear on quote/contract artifacts', 'Either party can be the comms point of contact'],                                                                                                                       type: 'feature', priority: 'low',      targetRelease: 'v1.9', points: 3, epicId: 'guided-configuration' },
    { title: '1.5.7 — Customer Document Storage',                             description: story('salesperson', 'to attach customer documents (driver\'s license, finance approval letters, ID) to the customer record', 'I have everything I need to close the deal in one place'),                  acceptanceCriteria: ['Document upload on customer detail sheet (PDF / image)', 'Document list with preview + download', 'Per-document description', 'Documents survive deletion of any single quote/contract'],                                                                                       type: 'feature', priority: 'low',      targetRelease: 'v1.9', points: 5, epicId: 'guided-configuration' },
    { title: '1.6.1 — Comms Log (unified interaction timeline)',              description: story('salesperson', 'every interaction with a customer (email sent, call made, note added, status changed) to land in one timeline per customer', 'I never have to reconstruct a relationship'),            acceptanceCriteria: ['Timeline merges notes (1.5.3), state transitions, sent quotes (1.4.2), emails when SMTP works', 'Each entry: type icon + timestamp + actor + body', 'Filter by interaction type', 'Inline note creation from the timeline'],                                                  type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 5, epicId: 'guided-configuration' },
    { title: '1.7.1 — Sales Pipeline Dashboard',                              description: story('sales manager', 'a dashboard showing total in-flight pipeline value, conversion rate, weighted forecast', 'I can run the team without spreadsheets'),                                                acceptanceCriteria: ['Total pipeline value (sum of weighted active quotes/contracts)', 'Conversion rate per stage', 'Per-salesperson breakdown', 'Per-brand breakdown', 'Filter by date range'],                                                                                                       type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 8, epicId: 'guided-configuration' },
    { title: '1.7.2 — My Quotes / My Customers / My Contracts views',         description: story('salesperson', 'salesperson-scoped views so I see only my work without filtering manually', 'my workspace is mine'),                                                                                    acceptanceCriteria: ['"My Quotes" view filters to current user', 'Same for customers and contracts', 'Toggle to "All" for sales managers', 'Default landing for non-managers is "My X"'],                                                                                                            type: 'feature', priority: 'high',     targetRelease: 'v1.9', points: 3, epicId: 'guided-configuration' },
    { title: '1.7.3 — Recent Activity Feed',                                  description: story('sales manager', 'a chronological feed of every important event across customers/quotes/contracts', 'I have ambient awareness of what the team is doing'),                                            acceptanceCriteria: ['Cross-customer activity stream', 'Filter by event type / salesperson', 'Click an entry to jump to the source artifact', 'Configurable retention (e.g. last 30 days)'],                                                                                                         type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 2, epicId: 'guided-configuration' },
    { title: '1.7.4 — Global Search',                                         description: story('salesperson', 'to search across customers / quotes / contracts / features from one place', 'I never lose 10 minutes hunting for a record'),                                                          acceptanceCriteria: ['Top-of-page search box', 'Searches title / customer name / quote number / contract number', 'Grouped result list', 'Keyboard shortcut (Cmd+K) opens it'],                                                                                                                       type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 3, epicId: 'guided-configuration' },

    // Epic 2 — Pricing Accuracy (5 stories, 23 pts → v1.8 + v1.9)
    { title: '2.1.1 — Structured Price Sources',                              description: story('finance stakeholder', 'all prices sourced from approved lists', 'pricing is accurate and auditable'),                                                  acceptanceCriteria: ['Prices originate from: Vendor/distributor price lists, Internal fit-out tables', 'Each line shows source reference & last updated date'], type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 2, epicId: 'pricing-accuracy' },
    { title: '2.1.2 — Model-Specific Fit-Out Pricing (Basic / Moderate / Complex)', description: story('salesperson', 'model-specific fit-out tiers', 'labour pricing matches reality'),                                                                acceptanceCriteria: ['Each model supports Basic / Moderate / Complex tiers', 'Pricing examples from spec: Stabicraft 2350 = $2,800 / $5,500 / $7,800; Surtees GF770 has different numbers for similar size'], type: 'feature', priority: 'high',     targetRelease: 'v1.8', points: 5, epicId: 'pricing-accuracy' },
    { title: '2.2.1 — Margin Threshold Enforcement + GM Override',            description: story('sales manager', 'low-margin quotes blocked by default', 'we protect profitability'),                                                                   acceptanceCriteria: ['Quotes below threshold cannot be sent', 'GM Sales & Marketing can override', 'Overrides are fully auditable'], type: 'feature', priority: 'high',     targetRelease: 'v1.8', points: 5, epicId: 'pricing-accuracy' },
    { title: '2.2.2 — Role-Based Margin Visibility',                          description: story('salesperson', 'simple margin signals', 'I know when a deal is healthy'),                                                                              acceptanceCriteria: ['Sales see Target margin %', 'Sales see Margin band (Green / Amber / Red)', 'Cost detail hidden where appropriate (e.g. internal fit-out items)'], type: 'feature', priority: 'medium',   targetRelease: 'v1.8', points: 3, epicId: 'pricing-accuracy' },
    { title: '2.3.1 — Quote Variations (post-contract)',                      description: story('salesperson', 'to make controlled changes after signing', 'customer changes are handled professionally'),                                              acceptanceCriteria: ['Items can be added or removed', 'Price delta clearly shown', 'Deal totals and margin recalculated', 'Original contract remains unchanged (locked baseline)'], type: 'feature', priority: 'high',     targetRelease: 'v1.9', points: 8, epicId: 'pricing-accuracy' },

    // Epic 2 expansion — Contract & Deposit (2.4.x), Order/Settlement (2.5.x), Variation docs (2.6.x), Margin admin (2.7.x)
    { title: '2.4.1 — Convert Quote → Contract',                              description: story('sales manager', 'an accepted quote to convert into a Contract record with its own state machine', 'we have a clear handover from sales to ops'),                                acceptanceCriteria: ['Accepted quote → "Convert to Contract" action', 'Contract is its own doc with: Drafted / Sent / Awaiting deposit / Deposit received / Build in progress / Ready for delivery / Delivered / Settled', 'Contract preserves the quote snapshot at acceptance time', 'Quote remains read-only after conversion'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'pricing-accuracy' },
    { title: '2.4.2 — Deposit Recording (with receipt PDF)',                  description: story('salesperson', 'to record a deposit against a contract and generate a receipt for the customer', 'cash handling has a paper trail'),                                              acceptanceCriteria: ['Deposit fields: amount, date, method (EFT / card / cash / cheque), reference', 'Receipt PDF auto-generated and attached to the contract', 'Outstanding balance recalculates', 'Deposit appears on customer comms log'], type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 5, epicId: 'pricing-accuracy' },
    { title: '2.4.3 — Payment Schedule',                                      description: story('finance stakeholder', 'a structured payment schedule on each contract (deposit + progress payments + final)', 'we can chase outstanding amounts and reconcile to Revolution'),       acceptanceCriteria: ['Schedule template: deposit (% on signing), milestones, final on delivery', 'Override schedule per contract', 'Each milestone has expected date + amount + status', 'Reminders surface when a milestone falls due'], type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 8, epicId: 'pricing-accuracy' },
    { title: '2.4.4 — Outstanding Balance Tracking',                          description: story('sales manager', 'to see the outstanding balance on every active contract at a glance', 'I can manage cashflow without spreadsheets'),                                                  acceptanceCriteria: ['Outstanding balance = contract total − sum(received payments)', 'Visible on contract detail + customer detail + dashboard', 'Aged buckets (current, 30d, 60d, 90d+)', 'Click-through to the contract to record a payment'],                                                          type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 3, epicId: 'pricing-accuracy' },
    { title: '2.4.5 — Refund Handling (cancellation flow)',                   description: story('sales manager', 'a structured way to record a refund when a customer cancels', 'cancellations are handled with audit trail and accurate reconciliation'),                              acceptanceCriteria: ['Cancellation reason capture', 'Refund amount + date + method recorded', 'Contract state transitions to "Cancelled"', 'Refund receipt PDF generated', 'Stock allocation released (links to 2.5.3)'],                                                                                  type: 'feature', priority: 'low',      targetRelease: 'Unscheduled', points: 3, epicId: 'pricing-accuracy' },
    { title: '2.4.6 — Final Invoice / Tax Invoice (settlement)',              description: story('finance stakeholder', 'a final tax invoice generated at settlement', 'we close the deal commercially with a compliant invoice'),                                                       acceptanceCriteria: ['ATO-compliant tax invoice fields (ABN, GST split, etc)', 'Auto-generated from contract data on settlement', 'Numbered sequentially per org', 'Stored alongside the contract', 'Posted to Revolution / accounting (links to 2.5.2)'],                                                  type: 'feature', priority: 'medium',   targetRelease: 'Unscheduled', points: 5, epicId: 'pricing-accuracy' },
    { title: '2.5.1 — Order Tracking (factory order lifecycle)',              description: story('ops', 'to track a factory order from "placed" through "shipped" to "arrived"', 'sales reps can give customers honest delivery ETAs'),                                                acceptanceCriteria: ['Order doc per contract: placed / confirmed / shipped / arrived / allocated', 'ETA field with revisions logged', 'Status visible on contract detail + customer detail', 'Auto-notification when ETA changes (when SMTP works)'],                                                       type: 'feature', priority: 'medium',   targetRelease: 'Unscheduled', points: 8, epicId: 'pricing-accuracy' },
    { title: '2.5.2 — Settlement Reconciliation to Revolution',               description: story('finance stakeholder', 'settlement to reconcile back to Revolution (ERP) with the actuals', 'HelmLogic stays trusted as the front-end and Revolution stays trusted as the books'),       acceptanceCriteria: ['Export final settlement payload', 'Mark contract as "Settled" with Revolution reference number', 'Variance report (HelmLogic forecast vs Revolution actual)', 'Manual override + reason for any discrepancies'],                                                                  type: 'feature', priority: 'low',      targetRelease: 'Unscheduled', points: 8, epicId: 'pricing-accuracy' },
    { title: '2.5.3 — Inventory Allocation to Contract',                      description: story('ops', 'when a contract is signed, mark the specific stock unit as allocated to that customer', 'two salespeople can never accidentally sell the same hull'),                          acceptanceCriteria: ['Contract → "Allocate stock" action picks an inventory unit', 'Inventory item state changes to "Allocated" with contract id', 'Concurrent-allocation lock (transaction)', 'De-allocation on contract cancellation', 'Hold-request flow integrates here'],                          type: 'feature', priority: 'high',     targetRelease: 'Unscheduled', points: 5, epicId: 'pricing-accuracy' },
    { title: '2.6.1 — Variation Order Document',                              description: story('sales manager', 'each variation to produce its own signed addendum PDF', 'every change after contract has its own paper trail'),                                                       acceptanceCriteria: ['Variation order PDF generated per variation', 'Includes: original contract reference, items added/removed, price delta, new total', 'Signed addendum stored alongside the contract', 'Printable / downloadable / emailable'],                                                       type: 'feature', priority: 'high',     targetRelease: 'v1.9', points: 3, epicId: 'pricing-accuracy' },
    { title: '2.6.2 — Variation History View',                                description: story('sales manager', 'a chronological list of every variation on a contract', 'I can audit how the deal evolved'),                                                                          acceptanceCriteria: ['Per-contract variation timeline', 'Each entry: date, actor, items changed, price delta, status', 'Click a variation → opens the variation order PDF', 'Cumulative net change visible at the top'],                                                                                type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 3, epicId: 'pricing-accuracy' },
    { title: '2.6.3 — Customer Agreement on Variation',                       description: story('salesperson', 'to record customer agreement to a variation before applying it', 'we have explicit consent for every change'),                                                          acceptanceCriteria: ['Variation in "Drafted" state until customer agrees', '"Mark agreed" action records customer + timestamp', 'Variation only applies to contract totals after agreement', 'E-sig deferred to a future release'],                                                                       type: 'feature', priority: 'high',     targetRelease: 'v1.9', points: 2, epicId: 'pricing-accuracy' },
    { title: '2.7.1 — Margin Threshold Configuration UI',                     description: story('sales manager', 'an admin UI to configure the margin threshold (the % below which 2.2.1 blocks sending)', 'we can tune the rule without redeploying'),                                  acceptanceCriteria: ['Threshold % set per brand', 'Override behaviour configurable per role (e.g. only GM)', 'Changes audit-logged', 'Quote send blocking respects the latest threshold'],                                                                                                            type: 'feature', priority: 'high',     targetRelease: 'v1.8', points: 3, epicId: 'pricing-accuracy' },

    // Epic 3 — Data Management (3 stories, 13 pts → v1.9)
    { title: '3.1.1 — Structured Data Imports + Versioning + Manual Approval', description: story('administrator', 'to import structured data', 'HelmLogic stays up to date efficiently'),                                                              acceptanceCriteria: ['Supports import of pricing, specs, photos, marketing copy', 'Versioning applied', 'Manual approval before publish'], type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 5, epicId: 'data-management' },
    { title: '3.2.1 — Internal Data Normalisation Layer',                     description: story('product owner', 'consistent internal data structures', 'quoting logic remains stable'),                                                                acceptanceCriteria: ['All imported data is normalised', 'NSM-specific overlays supported (descriptions, talking points, brand narrative)'], type: 'feature', priority: 'low',      targetRelease: 'v1.9', points: 3, epicId: 'data-management' },
    { title: '3.3.1 — Crowdsourced Suggestions with Audit',                   description: story('user', 'to flag errors or suggest improvements', 'data accuracy improves over time'),                                                                  acceptanceCriteria: ['Suggestions require review & publish by an authorised role', 'Full edit history retained', 'Sub-dealer permissions enforced (must not leak across brands/dealers)'], type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 5, epicId: 'data-management' },

    // Epic 3 expansion — Customer schema (3.4.1), Catalog admin UIs (3.4.2 / 3.4.3), Suggestion approval queue (3.5.1)
    { title: '3.4.1 — Customer Schema Redesign',                              description: story('product owner', 'the customer schema rebuilt to support all the new lifecycle / CRM features', 'the data model is no longer the bottleneck'),                                       acceptanceCriteria: ['Fields added: source, lifecycleStage, primaryBuyer + secondaryBuyer, tradeIn ref, documents[], notesCount', 'Existing customer docs migrate cleanly (defaults applied)', 'TypeScript types updated', 'Firestore rules + composite indexes ready'],                                  type: 'feature', priority: 'high',     targetRelease: 'v1.7', points: 3, epicId: 'data-management' },
    { title: '3.4.2 — Marketing Copy Editor UI',                              description: story('brand captain', 'an admin UI to edit imported marketing copy after it lands', 'NSM-specific overlays and tweaks happen in-app, not in spreadsheets'),                                acceptanceCriteria: ['Per-brand and per-model copy editor', 'TipTap rich text (same primitive as feature description)', 'Versioned: previous copy retained for diff/rollback', 'Live preview against the proposal PDF'],                                                                                  type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 5, epicId: 'data-management' },
    { title: '3.4.3 — Photo Curation UI',                                     description: story('brand captain', 'an admin UI to reorder, caption, and hide imported photos', 'the proposal hero images stay on-brand without re-importing the whole catalog'),                            acceptanceCriteria: ['Per-model photo grid with drag-to-reorder', 'Inline caption edit', '"Hide from proposals" toggle (keeps in catalog but excludes from PDF)', 'Bulk delete for imports gone wrong'],                                                                                              type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 3, epicId: 'data-management' },
    { title: '3.5.1 — Suggestion Approval Queue (completes 3.3.1)',           description: story('brand captain', 'a queue of pending crowdsourced suggestions with one-click approve / reject', 'data quality improvements actually ship instead of getting stuck'),                       acceptanceCriteria: ['Per-role approval queue (only authorised roles see it)', 'Approve → suggested change applied + audit log entry', 'Reject → suggester notified with reason', 'Filter by data type (pricing / specs / copy / photos)'],                                                            type: 'feature', priority: 'high',     targetRelease: 'v1.8', points: 3, epicId: 'data-management' },

    // Epic 4 — Promotions (2 stories, 6 pts → v1.9)
    { title: '4.1.1 — Promotion Entry (manual, all forms)',                   description: story('salesperson', 'to manually enter promotions', 'real-world deals can be quoted'),                                                                       acceptanceCriteria: ['Supports $ off per HP', 'Supports $ off per foot', 'Supports % off specific item', 'Supports fixed rebate', 'Applies at brand, model, or component level'], type: 'feature', priority: 'high',     targetRelease: 'v1.9', points: 3, epicId: 'promotions' },
    { title: '4.1.2 — Promotion Alerts',                                      description: story('salesperson', 'to be alerted to active promotions', "I don't miss opportunities"),                                                                     acceptanceCriteria: ['Alerts shown when applicable', 'Promotions are date-bounded', 'Promotions are NOT auto-applied (manual for MVP)'], type: 'feature', priority: 'medium',   targetRelease: 'v1.9', points: 3, epicId: 'promotions' },

    // Epic 4 expansion — Promo edge cases (4.2.x)
    { title: '4.2.1 — Promotion Stacking Rules',                              description: story('sales manager', 'to define whether multiple promotions can apply to one quote (and which combos are valid)', 'we avoid accidental over-discounting'),                              acceptanceCriteria: ['Per-promo "stackable" flag', 'Stacking matrix: which promos combine', 'Enforced at quote-build time with a warning toast on collision'],                                                                                                                                       type: 'feature', priority: 'low',      targetRelease: 'Unscheduled', points: 3, epicId: 'promotions' },
    { title: '4.2.2 — Customer-Specific Promotions',                          description: story('sales manager', 'to assign promotions to specific customers (fleet, loyalty, key account)', 'the right pricing reaches the right customer automatically'),                          acceptanceCriteria: ['Promo can target a customer (or list of customers)', 'Visible only when quoting for that customer', 'Auto-suggested at quote build (still manual-apply per 4.1.2)'],                                                                                                            type: 'feature', priority: 'low',      targetRelease: 'Unscheduled', points: 5, epicId: 'promotions' },

    // Epic 5 — Security & Extensibility (3 stories, 16 pts → v2.0)
    { title: '5.1.1 — Flexible Quoting Units (hull-only, engine-only, trailer-only)', description: story('salesperson', 'to quote individual components', 'HelmLogic works beyond full boat sales'),                                                    acceptanceCriteria: ['Can quote hull-only', 'Can quote engine-only', 'Can quote trailer-only', 'Configuration rules are modular, not hard-wired to "boat = required"'], type: 'feature', priority: 'high',     targetRelease: 'v2.0', points: 5, epicId: 'security-extensibility' },
    { title: '5.2.1 — Brand & Dealer Isolation (RBAC + leakage tests)',       description: story('platform owner', 'strict access controls', 'commercial data is protected'),                                                                            acceptanceCriteria: ['Users see only authorised brands (e.g. Marine Trade Supplies sees Highfield only)', "Sub-dealers cannot see other dealers' quotes / opportunities", 'Pricing visibility is role-controlled', 'Crowdsourcing permissions are restricted', 'Leakage tests covering cross-brand AND cross-dealer scenarios'], type: 'feature', priority: 'critical', targetRelease: 'v2.0', points: 8, epicId: 'security-extensibility' },
    { title: '5.3.1 — Brand Onboarding Without Code',                         description: story('product owner', 'to add brands without deployment changes', 'HelmLogic can scale safely'),                                                              acceptanceCriteria: ['Brand onboarding is data-driven', 'Quoting logic remains isolated per brand', 'Documented playbook for onboarding a new brand end-to-end'], type: 'feature', priority: 'medium',   targetRelease: 'v2.0', points: 3, epicId: 'security-extensibility' },

    // Epic 5 expansion — Customer access (5.4.x), Audit / Compliance (5.5.x)
    { title: '5.4.1 — Customer Access Control',                               description: story('platform owner', 'to control which salesperson sees which customers', 'sales territories and key-account segregation are enforceable'),                                              acceptanceCriteria: ['Per-customer visibility: assigned salesperson(s) + sales manager + admin', 'Default: assigned salesperson + their manager', 'Sub-dealer customers never visible cross-dealer', 'Override at customer detail sheet'],                                                            type: 'feature', priority: 'medium',   targetRelease: 'Unscheduled', points: 5, epicId: 'security-extensibility' },
    { title: '5.5.1 — Universal Activity Log',                                description: story('platform owner', 'every important state change in the system to land in a queryable activity log', 'we have a defensible audit trail and trust artifact'),                          acceptanceCriteria: ['Every state change captured: quote sent, accepted, deposit recorded, variation agreed, role change, etc', 'Each entry: timestamp + actor + entity ref + change diff', 'Admin-only activity log view with filter + export'],                                                     type: 'feature', priority: 'medium',   targetRelease: 'v2.0', points: 8, epicId: 'security-extensibility' },
    { title: '5.5.2 — T&C Versioning',                                        description: story('legal owner', 'multiple versions of the T&Cs stored, with each contract linked to the version that was in force at signing', 'we are defensible if T&Cs change and a customer disputes'), acceptanceCriteria: ['T&C documents with effective dates', 'Contracts capture the T&C version at signing', 'Old versions remain immutable', 'Version diff viewer'],                                                                                                                                    type: 'feature', priority: 'medium',   targetRelease: 'Unscheduled', points: 3, epicId: 'security-extensibility' },
    { title: '5.5.3 — State-Specific Compliance',                             description: story('legal owner', 'state-specific regulatory requirements (cooling-off periods, mandatory disclosures) to be reflected on contracts', 'we comply with AU consumer law per jurisdiction'),  acceptanceCriteria: ['State picker on customer (NSW / VIC / QLD / WA / SA / TAS / NT / ACT)', 'State-specific T&C clauses inserted into the signing pack', 'Cooling-off period reflected in contract state machine', 'Documented review process for changes'],                                          type: 'feature', priority: 'medium',   targetRelease: 'Unscheduled', points: 5, epicId: 'security-extensibility' },
    { title: '5.5.4 — Privacy / Data Deletion',                               description: story('platform owner', 'a workflow to delete a customer\'s personal data on request (GDPR-style)', 'we satisfy privacy obligations without a bespoke ops process'),                              acceptanceCriteria: ['"Right to be forgotten" action on customer detail (admin only)', 'Personal fields anonymised; commercial records (totals, contracts) retained', 'Deletion logged in activity log', 'Reversible window (7 days) before hard delete'],                                              type: 'feature', priority: 'low',      targetRelease: 'Unscheduled', points: 3, epicId: 'security-extensibility' },

    // ---------------------------------------------------------------------
    // CONTENT items — 14 deliverables the business has to write/produce.
    // Type: 'content'. Most block specific code features (1.2.x / 1.3.2 etc).
    // No story points (per popup decision: skip points on non-code).
    // ---------------------------------------------------------------------
    { title: '"Why Northside Marine" copy',                       description: '<p><strong>Deliverable:</strong> Hero positioning paragraph for the proposal PDF — what makes NSM different. Drives 1.2.1 Branded PDF Quote Generation.</p>',                                                                                acceptanceCriteria: ['Drafted by marketing', 'Approved by GM Sales & Marketing', 'Loaded into HelmLogic per-brand template'],                                                                                                       type: 'content',  priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: '"Life Beyond the Shore" positioning copy',          description: '<p><strong>Deliverable:</strong> The brand promise that makes the proposal feel emotional, not transactional. Drives 1.2.1.</p>',                                                                                                                  acceptanceCriteria: ['Drafted by marketing', 'Approved by GM Sales & Marketing', 'Loaded into HelmLogic'],                                                                                                                          type: 'content',  priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'Brand stories (Highfield / Stabicraft / Surtees / Stacer / Yamaha / 6th brand)', description: '<p><strong>Deliverable:</strong> One emotionally resonant brand story per brand carried by HelmLogic. Drives 1.2.2 Brand-Aware Content Injection.</p>',                                                       acceptanceCriteria: ['Story drafted per brand (6 total)', 'Approved by each brand captain', 'Loaded into vendor docs'],                                                                                                            type: 'content',  priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'Per-model hero copy',                               description: '<p><strong>Deliverable:</strong> Short hero paragraph per boat model (e.g. CL260, GF770) for the proposal PDF. Drives 1.2.2.</p>',                                                                                                                acceptanceCriteria: ['Copy drafted for every model in the catalog', 'Approved by brand captain', 'Loaded into model docs'],                                                                                                        type: 'content',  priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'Salesperson message templates',                     description: '<p><strong>Deliverable:</strong> 3-5 starter templates for the personalised salesperson message section of the proposal. Lets sales reps customise without writing from scratch. Drives 1.2.3 Controlled Personalisation.</p>',                acceptanceCriteria: ['Templates drafted', 'Approved by sales leadership', 'Available as a picker on the create-quote flow'],                                                                                                       type: 'content',  priority: 'medium',   targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'Terms & Conditions text',                           description: '<p><strong>Deliverable:</strong> The legal T&Cs that ship with every signing pack. Likely per-brand and per-state variants. Blocks 1.3.2 Contract Signing Pack Generation.</p>',                                                                acceptanceCriteria: ['Drafted by legal counsel', 'Vetted for AU consumer law', 'Versioned (links to 5.5.2)', 'Loaded into HelmLogic'],                                                                                              type: 'content',  priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'Payment plan default text',                         description: '<p><strong>Deliverable:</strong> The "Payment plan expectations" section of the signing pack — explains deposit, milestones, final payment in customer-friendly language. Blocks 1.3.2.</p>',                                                  acceptanceCriteria: ['Drafted by sales leadership', 'Reviewed by finance', 'Approved by GM Sales & Marketing', 'Loaded into the signing pack template'],                                                                          type: 'content',  priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'Email templates (quote sent / variation / payment reminder)', description: '<p><strong>Deliverable:</strong> Standard email body templates for the three core customer-facing notifications. Used once email integration is restored.</p>',                                                                       acceptanceCriteria: ['3 templates drafted (sent, variation, reminder)', 'Approved by sales leadership', 'Stored in mail collection templates'],                                                                                    type: 'content',  priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'guided-configuration' },
    { title: 'Email signature standard',                          description: '<p><strong>Deliverable:</strong> Branded HTML email signature with logo, salesperson name, contact details. Used by the email integration.</p>',                                                                                                  acceptanceCriteria: ['HTML signature drafted', 'Per-salesperson personalisation tokens', 'Approved by marketing'],                                                                                                                  type: 'content',  priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'guided-configuration' },
    { title: 'Receipt PDF branding',                              description: '<p><strong>Deliverable:</strong> Visual design + boilerplate text for the deposit receipt PDF. Blocks 2.4.2 Deposit Recording.</p>',                                                                                                              acceptanceCriteria: ['PDF template designed', 'Brand-correct logo + colours', 'Includes all legally-required receipt fields (ABN, GST, etc)'],                                                                                     type: 'content',  priority: 'medium',   targetRelease: 'v1.7',        points: null, epicId: 'pricing-accuracy' },
    { title: 'Variation order PDF template',                      description: '<p><strong>Deliverable:</strong> Visual + textual template for the variation order document customers sign. Blocks 2.6.1 Variation Order Document.</p>',                                                                                          acceptanceCriteria: ['Template designed', 'Includes original-contract reference, items changed, price delta, new total', 'Legal review'],                                                                                          type: 'content',  priority: 'medium',   targetRelease: 'v1.9',        points: null, epicId: 'pricing-accuracy' },
    { title: 'Tax invoice template',                              description: '<p><strong>Deliverable:</strong> ATO-compliant tax invoice template for settlement. Blocks 2.4.6 Final Invoice.</p>',                                                                                                                            acceptanceCriteria: ['ATO-compliant fields', 'Numbered sequentially per org', 'Brand-correct visual', 'Reviewed by finance'],                                                                                                       type: 'content',  priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'pricing-accuracy' },
    { title: 'Cooling-off legal text per state',                  description: '<p><strong>Deliverable:</strong> Australian state-specific cooling-off period clauses to insert into signing packs. Blocks 5.5.3 State-Specific Compliance.</p>',                                                                                acceptanceCriteria: ['Text per state where NSM operates (NSW / VIC / QLD / etc)', 'Vetted by legal counsel', 'Versioned (links to 5.5.2)'],                                                                                          type: 'content',  priority: 'medium',   targetRelease: 'Unscheduled', points: null, epicId: 'security-extensibility' },
    { title: 'Privacy disclosure text',                           description: '<p><strong>Deliverable:</strong> Privacy notice shown to customers when their data is captured (consent at quote/contract stage). Blocks 5.5.4 Privacy / Data Deletion.</p>',                                                                    acceptanceCriteria: ['Drafted by legal', 'Compliant with Australian Privacy Principles', 'Linked from customer detail sheet'],                                                                                                     type: 'content',  priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'security-extensibility' },

    // ---------------------------------------------------------------------
    // DECISION items — 16 business decisions that gate specific code
    // features. Type: 'decision' (⚖️). Points: null per popup decision.
    // ---------------------------------------------------------------------
    { title: 'Margin threshold % per brand',                            description: '<p><strong>Decision:</strong> What is the agreed minimum margin % below which a quote cannot be sent without GM override? Likely different per brand (Highfield vs Stacer etc). Blocks 2.2.1 Margin Threshold Enforcement.</p>',          acceptanceCriteria: ['Threshold % set per brand', 'Approved by GM Sales & Marketing', 'Loaded into the threshold config UI when 2.7.1 ships'],                                                            type: 'decision', priority: 'high',     targetRelease: 'v1.8',        points: null, epicId: 'pricing-accuracy' },
    { title: 'Fit-out tier pricing per model (Basic / Moderate / Complex)', description: '<p><strong>Decision:</strong> The actual $ value of Basic / Moderate / Complex fit-out for EVERY model in the catalog. Spec example: Stabicraft 2350 = $2,800 / $5,500 / $7,800. Blocks 2.1.2 Model-Specific Fit-Out Pricing.</p>',  acceptanceCriteria: ['Three tier prices captured per model', 'Approved by sales leadership + finance', 'Loaded into model docs'],                                                                          type: 'decision', priority: 'high',     targetRelease: 'v1.8',        points: null, epicId: 'pricing-accuracy' },
    { title: 'Default payment schedule (% deposit / milestones / final)', description: '<p><strong>Decision:</strong> Standard payment plan template — what % is the deposit, what milestones trigger progress payments, when is the final due. Blocks 2.4.3 Payment Schedule.</p>',                                              acceptanceCriteria: ['Default schedule defined (e.g. 10% deposit / 30% on order / 60% on delivery)', 'Override per contract still possible', 'Approved by finance'],                                       type: 'decision', priority: 'medium',   targetRelease: 'v1.9',        points: null, epicId: 'pricing-accuracy' },
    { title: 'Default deposit amount / formula',                        description: '<p><strong>Decision:</strong> What\'s the default deposit on a new contract? Fixed $ vs % of contract value? Blocks 2.4.2 Deposit Recording.</p>',                                                                                          acceptanceCriteria: ['Default formula or amount', 'Per-brand overrides possible', 'Approved by finance + sales leadership'],                                                                              type: 'decision', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'pricing-accuracy' },
    { title: 'GM override authority — who?',                            description: '<p><strong>Decision:</strong> Which user / role has authority to override the margin threshold (and any other gating rule)? Likely "GM Sales & Marketing". Blocks 2.2.1.</p>',                                                                acceptanceCriteria: ['Named user(s) identified', 'Role assignment captured in HelmLogic', 'Override action audited'],                                                                                      type: 'decision', priority: 'high',     targetRelease: 'v1.8',        points: null, epicId: 'pricing-accuracy' },
    { title: 'Refund policy',                                           description: '<p><strong>Decision:</strong> Under what conditions do we refund a deposit? What % do we keep? Blocks 2.4.5 Refund Handling.</p>',                                                                                                          acceptanceCriteria: ['Policy drafted', 'Reviewed by legal', 'Aligned with cooling-off periods per state', 'Approved by GM Sales & Marketing'],                                                            type: 'decision', priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'pricing-accuracy' },
    { title: 'Customer pipeline stages',                                description: '<p><strong>Decision:</strong> The lifecycle stages a customer moves through (lead → ??? → won → delivered). Drives the Pipeline View Kanban columns. Blocks 1.5.2 Customer Pipeline View.</p>',                                                acceptanceCriteria: ['Stage list locked', 'Approved by sales leadership', 'Stages match how the team actually thinks about the funnel'],                                                                  type: 'decision', priority: 'high',     targetRelease: 'v1.8',        points: null, epicId: 'guided-configuration' },
    { title: 'Quote validity period default',                           description: '<p><strong>Decision:</strong> How many days is a quote valid before auto-expiring? Per-brand default? Blocks 1.4.4 Quote Validity / Expiry.</p>',                                                                                            acceptanceCriteria: ['Default period agreed (e.g. 30 days)', 'Per-brand override possible', 'Approved by sales leadership'],                                                                              type: 'decision', priority: 'medium',   targetRelease: 'v1.8',        points: null, epicId: 'guided-configuration' },
    { title: 'Customer source dropdown options',                        description: '<p><strong>Decision:</strong> The list of "how did you hear about us?" options shown when creating a customer. Boat show / referral / web / walk-in / etc. Blocks 1.5.4 Customer Source Tracking.</p>',                                       acceptanceCriteria: ['Source list drafted', 'Approved by marketing', 'Option for "Other" with free-text override'],                                                                                       type: 'decision', priority: 'low',      targetRelease: 'v1.8',        points: null, epicId: 'guided-configuration' },
    { title: 'Trade-in valuation rules',                                description: '<p><strong>Decision:</strong> How is a trade-in vessel valued? External appraisal? Internal formula? Approval workflow if outside band? Blocks 1.5.5 Trade-In Record.</p>',                                                                  acceptanceCriteria: ['Valuation methodology agreed', 'Approval threshold defined', 'Approved by GM Sales & Marketing'],                                                                                    type: 'decision', priority: 'medium',   targetRelease: 'v1.9',        points: null, epicId: 'guided-configuration' },
    { title: 'SharePoint folder convention',                            description: '<p><strong>Decision:</strong> What folder structure does HelmLogic write quotes into on SharePoint? e.g. /Quotes/{Year}/{Customer-QuoteNumber}.pdf. Blocks 1.3.3 SharePoint Quote Storage.</p>',                                              acceptanceCriteria: ['Folder convention agreed with IT', 'Naming scheme captured (year, customer name, quote number)', 'Documented in HelmLogic config'],                                                  type: 'decision', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'SharePoint access permissions',                           description: '<p><strong>Decision:</strong> Who can read each quote folder on SharePoint? All staff? Per-brand? Per-org? Blocks 1.3.3.</p>',                                                                                                              acceptanceCriteria: ['Permission matrix agreed', 'Configured in SharePoint by IT', 'Documented'],                                                                                                          type: 'decision', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'guided-configuration' },
    { title: 'E-signature provider choice',                             description: '<p><strong>Decision:</strong> When we add e-signature for variations + acceptance later, do we use DocuSign / Adobe Sign / built-in / a different provider? Affects 1.4.3, 2.6.3 architectures.</p>',                                       acceptanceCriteria: ['Provider chosen', 'Cost model approved', 'Integration approach scoped'],                                                                                                             type: 'decision', priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'guided-configuration' },
    { title: 'Crowdsourcing approval authority — who?',                 description: '<p><strong>Decision:</strong> Which user / role can approve crowdsourced data suggestions? Per-brand "brand captain"? Specific admins? Blocks 3.5.1 Suggestion Approval Queue.</p>',                                                        acceptanceCriteria: ['Authority assignment captured', 'Per-data-type rules (pricing → finance, copy → marketing, etc)'],                                                                                   type: 'decision', priority: 'medium',   targetRelease: 'v1.8',        points: null, epicId: 'data-management' },
    { title: 'Which Australian states do we operate in?',               description: '<p><strong>Decision:</strong> The list of states NSM (and sub-dealers) actively sell into — drives state-specific compliance work. Blocks 5.5.3 State-Specific Compliance.</p>',                                                          acceptanceCriteria: ['State list captured', 'Per-state cooling-off periods documented', 'Per-state regulatory disclosures noted'],                                                                         type: 'decision', priority: 'medium',   targetRelease: 'Unscheduled', points: null, epicId: 'security-extensibility' },
    { title: 'Salesperson territory / customer assignment rules',       description: '<p><strong>Decision:</strong> How are customers assigned to salespeople? Geographic territory? Brand specialism? Round-robin lead allocation? Drives 5.4.1 Customer Access Control.</p>',                                                    acceptanceCriteria: ['Rule set documented', 'Approved by sales leadership', 'Codified into HelmLogic role/permission model'],                                                                              type: 'decision', priority: 'medium',   targetRelease: 'Unscheduled', points: null, epicId: 'security-extensibility' },

    // ---------------------------------------------------------------------
    // OPS / TASK items — 16 launch-prep activities. Type: 'task' (📋).
    // All under Epic 6 'Launch Prep & Ops'. Points: null (per popup).
    // ---------------------------------------------------------------------
    { title: 'Azure AD app registration for SharePoint',          description: '<p><strong>Activity:</strong> Register an Azure AD application with Files.ReadWrite.All on the target SharePoint site. Provide HelmLogic with the client id + secret. Gates 1.3.3 SharePoint Quote Storage.</p>',                                                              acceptanceCriteria: ['App registered in tenant', 'Files.ReadWrite.All admin consent granted', 'Client id + secret provided to HelmLogic env'],                                                              type: 'task', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Tester recruitment + feedback channel',             description: '<p><strong>Activity:</strong> Identify 3-5 testers from the sales team to use HelmLogic on dev daily. Set up a clear feedback channel (in-app feature suggestions, Slack channel, weekly review). Currently in flight.</p>',                                                acceptanceCriteria: ['Testers named', 'Feedback channel chosen', 'Weekly cadence agreed', 'First feedback within 7 days'],                                                                                  type: 'task', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Photo library audit',                               description: '<p><strong>Activity:</strong> Walk every model in the catalog. Mark each photo as demo-quality / needs-replacement / hide. Flag missing hero shots that need new photography. Drives 1.2.2 Brand-Aware Content + 3.4.3 Photo Curation UI.</p>',                              acceptanceCriteria: ['Per-model photo audit complete', 'Replacement shoot list compiled', 'New shoots scheduled if needed'],                                                                                type: 'task', priority: 'medium',   targetRelease: 'v1.7',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Multi-brand asset gathering',                       description: '<p><strong>Activity:</strong> Collect logos, hero imagery, brand colour codes, and font choices for every brand in HelmLogic (6 brands at MVP). Drives 1.2.1 Branded PDF Quote Generation.</p>',                                                                                  acceptanceCriteria: ['Logo files (high-res, transparent BG) per brand', 'Hero image library per brand', 'Brand style guide referenced', 'Loaded into vendor docs in HelmLogic'],                            type: 'task', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Legal review of T&Cs',                              description: '<p><strong>Activity:</strong> Engage legal counsel to review the T&C draft we ship in the signing pack. Per-brand and per-state variants if needed. Gates 1.3.2 Contract Signing Pack Generation.</p>',                                                                          acceptanceCriteria: ['Legal counsel engaged', 'T&C reviewed and edited', 'Sign-off from GM Sales & Marketing', 'Loaded into HelmLogic'],                                                                   type: 'task', priority: 'high',     targetRelease: 'v1.7',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Build training plan',                               description: '<p><strong>Activity:</strong> Define training format (in-person session vs Zoom vs cheat sheet vs video walk-through), content per role (sales / managers / admins), and duration.</p>',                                                                                          acceptanceCriteria: ['Format chosen', 'Content outline drafted', 'Time estimate per session', 'Approved by GM Sales & Marketing'],                                                                          type: 'task', priority: 'medium',   targetRelease: 'v1.8',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Schedule training sessions per role',               description: '<p><strong>Activity:</strong> Book actual training sessions on the calendar. Per-role attendance list. Recorded for asynchronous catch-up.</p>',                                                                                                                                acceptanceCriteria: ['Sessions booked on calendar', 'Attendance list per session', 'Recording arrangements confirmed'],                                                                                    type: 'task', priority: 'medium',   targetRelease: 'v1.9',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Comms plan: announce HelmLogic to sales team',      description: '<p><strong>Activity:</strong> Internal launch communications — email announcement, all-hands demo, FAQ doc, escalation path for issues.</p>',                                                                                                                                  acceptanceCriteria: ['Announcement email drafted', 'All-hands demo booked', 'FAQ doc published', 'Escalation contact named'],                                                                               type: 'task', priority: 'medium',   targetRelease: 'v1.9',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Pull existing customer list from current CRM',      description: '<p><strong>Activity:</strong> Export current customer records from the existing tool (whatever it is). Clean, dedupe, map fields to HelmLogic schema. Import.</p>',                                                                                                            acceptanceCriteria: ['Source export obtained', 'Field-mapping defined', 'Deduplication run', 'Imported into customers/{id} collection', 'Spot-check verified by sales'],                                  type: 'task', priority: 'medium',   targetRelease: 'v2.0',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Pull existing quote/contract data from Revolution', description: '<p><strong>Activity:</strong> Decide what historical quote / contract data (if any) gets imported into HelmLogic. Likely just open / in-flight ones, not the full history.</p>',                                                                                                acceptanceCriteria: ['Migration scope agreed (which records to import)', 'Export from Revolution obtained', 'Field-mapping defined', 'Imported and verified'],                                              type: 'task', priority: 'medium',   targetRelease: 'v2.0',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Migration cutoff date decision',                    description: '<p><strong>Activity:</strong> Pick the date after which all NEW quotes go in HelmLogic only. Old tool stays read-only for in-flight deals. Set expectations.</p>',                                                                                                              acceptanceCriteria: ['Cutoff date locked', 'Approved by GM Sales & Marketing', 'Communicated to entire sales team'],                                                                                       type: 'task', priority: 'medium',   targetRelease: 'v2.0',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Decommission old tool / parallel run plan',         description: '<p><strong>Activity:</strong> Plan the wind-down of the old quoting tool. Parallel-run period? Read-only freeze date? Final cut-over.</p>',                                                                                                                                    acceptanceCriteria: ['Wind-down plan documented', 'Read-only freeze date', 'Final cut-over date', 'Stakeholders briefed'],                                                                                  type: 'task', priority: 'medium',   targetRelease: 'v2.0',        points: null, epicId: 'launch-prep-ops' },
    { title: 'Privacy policy update',                             description: '<p><strong>Activity:</strong> Update the NSM privacy policy to cover HelmLogic-handled customer data. Aligned with Australian Privacy Principles.</p>',                                                                                                                        acceptanceCriteria: ['Privacy policy reviewed', 'Updates drafted', 'Legal sign-off', 'Published'],                                                                                                          type: 'task', priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'launch-prep-ops' },
    { title: 'Insurance review',                                  description: '<p><strong>Activity:</strong> Confirm with insurer that customer data handled in HelmLogic is covered under existing cyber/professional indemnity policies. Adjust cover if needed.</p>',                                                                                       acceptanceCriteria: ['Broker engaged', 'Policy reviewed', 'Adjustments made if needed', 'Documented'],                                                                                                      type: 'task', priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'launch-prep-ops' },
    { title: 'Office 365 SMTP debug — get email working',         description: '<p><strong>Activity:</strong> Resolve the SMTP-not-sending issue with the Trigger Email extension. Likely "Authentication failed" or "Sender address rejected" — needs SMTP AUTH enabled on the mailbox + correct app password URL-encoded. Currently parked.</p>',                acceptanceCriteria: ['SMTP URI debug', 'Mailbox SMTP AUTH enabled', 'Test email sent + received', 'Email integration unblocks @-mentions and other email features'],                                       type: 'task', priority: 'medium',   targetRelease: 'Unscheduled', points: null, epicId: 'launch-prep-ops' },
    { title: 'Revolution integration architecture call',          description: '<p><strong>Activity:</strong> Decide HOW HelmLogic talks to Revolution at settlement. CSV export? API? Manual reconciliation? Affects 2.5.2 Settlement Reconciliation.</p>',                                                                                                    acceptanceCriteria: ['Architecture discussion held with Revolution admins', 'Approach chosen', 'Documented', 'Effort scoped'],                                                                              type: 'task', priority: 'low',      targetRelease: 'Unscheduled', points: null, epicId: 'launch-prep-ops' },
];

export interface SeedSummary {
    epicsCreated: number;
    epicsSkipped: number;
    featuresCreated: number;
    featuresSkipped: number;
}

/**
 * Run the seeder. Idempotent — re-running after a successful seed
 * results in 0 created / 27 skipped.
 */
export async function seedMvpPlan(
    firestore: Firestore,
    submitterUid: string | undefined,
    submitterName: string,
): Promise<SeedSummary> {
    let epicsCreated = 0;
    let epicsSkipped = 0;
    let featuresCreated = 0;
    let featuresSkipped = 0;

    // Epics: stable slug ids, getDoc → create-if-missing.
    for (const epic of EPICS) {
        const ref = doc(firestore, 'epics', epic.id);
        const snap = await getDoc(ref);
        if (snap.exists()) {
            epicsSkipped++;
            continue;
        }
        await setDoc(ref, {
            title: epic.title,
            shortLabel: epic.shortLabel,
            description: epic.description,
            color: epic.color,
            order: epic.order,
            status: epic.status,
            createdAt: serverTimestamp(),
            updatedAt: serverTimestamp(),
        });
        epicsCreated++;
    }

    // Features: list once, dedupe by title (the spec's "1.1.1 — ..."
    // numbering means collisions are effectively impossible).
    const existing = await getDocs(collection(firestore, 'features'));
    const existingTitles = new Set<string>();
    existing.forEach(d => {
        const t = (d.data().title as string | undefined)?.trim();
        if (t) existingTitles.add(t);
    });

    for (const f of FEATURES) {
        if (existingTitles.has(f.title.trim())) {
            featuresSkipped++;
            continue;
        }
        await addDoc(collection(firestore, 'features'), {
            title: f.title,
            description: f.description,
            acceptanceCriteria: f.acceptanceCriteria,
            type: f.type,
            status: 'submitted',
            priority: f.priority,
            targetRelease: f.targetRelease,
            points: f.points,
            epicId: f.epicId,
            tags: [],
            voteIds: [],
            imageUrls: [],
            commentCount: 0,
            deletedAt: null,
            deletedBy: null,
            order: 0,
            submitterId: submitterUid ?? 'seed-mvp-plan',
            submitterName,
            createdAt: serverTimestamp(),
            updatedAt: serverTimestamp(),
        });
        featuresCreated++;
    }

    return { epicsCreated, epicsSkipped, featuresCreated, featuresSkipped };
}
